/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthenticatedInventoryWarehouseIndexRouteImport } from './routes/_authenticated/inventory/warehouse.index'
import { Route as AuthenticatedInventoryVendorsIndexRouteImport } from './routes/_authenticated/inventory/vendors.index'
import { Route as AuthenticatedInventoryServiceIndexRouteImport } from './routes/_authenticated/inventory/service.index'
import { Route as AuthenticatedInventoryServiceInvoiceIndexRouteImport } from './routes/_authenticated/inventory/service-invoice.index'
import { Route as AuthenticatedInventorySalesIndexRouteImport } from './routes/_authenticated/inventory/sales.index'
import { Route as AuthenticatedInventoryQuotationIndexRouteImport } from './routes/_authenticated/inventory/quotation.index'
import { Route as AuthenticatedInventoryPurchaseIndexRouteImport } from './routes/_authenticated/inventory/purchase.index'
import { Route as AuthenticatedInventoryProductIndexRouteImport } from './routes/_authenticated/inventory/product.index'
import { Route as AuthenticatedInventoryMerchantIndexRouteImport } from './routes/_authenticated/inventory/merchant.index'
import { Route as AuthenticatedInventoryWarehouseStockMovementRouteImport } from './routes/_authenticated/inventory/warehouse.stock-movement'
import { Route as AuthenticatedInventoryWarehouseCreateRouteImport } from './routes/_authenticated/inventory/warehouse.create'
import { Route as AuthenticatedInventoryVendorsCreateRouteImport } from './routes/_authenticated/inventory/vendors.create'
import { Route as AuthenticatedInventoryServiceInvoiceCreateRouteImport } from './routes/_authenticated/inventory/service-invoice.create'
import { Route as AuthenticatedInventorySalesTermsRouteImport } from './routes/_authenticated/inventory/sales.terms'
import { Route as AuthenticatedInventorySalesPaymentsRouteImport } from './routes/_authenticated/inventory/sales.payments'
import { Route as AuthenticatedInventorySalesCreateRouteImport } from './routes/_authenticated/inventory/sales.create'
import { Route as AuthenticatedInventorySalesContactUsRouteImport } from './routes/_authenticated/inventory/sales.contact-us'
import { Route as AuthenticatedInventoryQuotationCreateRouteImport } from './routes/_authenticated/inventory/quotation.create'
import { Route as AuthenticatedInventoryPurchaseCreateRouteImport } from './routes/_authenticated/inventory/purchase.create'
import { Route as AuthenticatedInventoryProductUnitRouteImport } from './routes/_authenticated/inventory/product.unit'
import { Route as AuthenticatedInventoryProductSubCategoryRouteImport } from './routes/_authenticated/inventory/product.sub-category'
import { Route as AuthenticatedInventoryProductCreateRouteImport } from './routes/_authenticated/inventory/product.create'
import { Route as AuthenticatedInventoryProductCategoryRouteImport } from './routes/_authenticated/inventory/product.category'
import { Route as AuthenticatedInventoryMerchantCreateRouteImport } from './routes/_authenticated/inventory/merchant.create'
import { Route as AuthenticatedInventoryReturnWastageIndexRouteImport } from './routes/_authenticated/inventory/return.wastage.index'
import { Route as AuthenticatedInventoryReturnVendorIndexRouteImport } from './routes/_authenticated/inventory/return.vendor.index'
import { Route as AuthenticatedInventoryReturnMerchantIndexRouteImport } from './routes/_authenticated/inventory/return.merchant.index'
import { Route as AuthenticatedInventoryWarehouseStockMovementCreateRouteImport } from './routes/_authenticated/inventory/warehouse.stock-movement.create'
import { Route as AuthenticatedInventoryWarehouseEditIdRouteImport } from './routes/_authenticated/inventory/warehouse.edit.$id'
import { Route as AuthenticatedInventoryVendorsEditIdRouteImport } from './routes/_authenticated/inventory/vendors.edit.$id'
import { Route as AuthenticatedInventoryServiceInvoiceViewIdRouteImport } from './routes/_authenticated/inventory/service-invoice.view.$id'
import { Route as AuthenticatedInventoryServiceInvoiceEditIdRouteImport } from './routes/_authenticated/inventory/service-invoice.edit.$id'
import { Route as AuthenticatedInventorySalesViewIdRouteImport } from './routes/_authenticated/inventory/sales.view.$id'
import { Route as AuthenticatedInventorySalesPrintIdRouteImport } from './routes/_authenticated/inventory/sales.print.$id'
import { Route as AuthenticatedInventorySalesEditIdRouteImport } from './routes/_authenticated/inventory/sales.edit.$id'
import { Route as AuthenticatedInventoryReturnVendorCreateRouteImport } from './routes/_authenticated/inventory/return.vendor.create'
import { Route as AuthenticatedInventoryQuotationViewIdRouteImport } from './routes/_authenticated/inventory/quotation.view.$id'
import { Route as AuthenticatedInventoryQuotationEditIdRouteImport } from './routes/_authenticated/inventory/quotation.edit.$id'
import { Route as AuthenticatedInventoryQuotationAddToInvoiceIdRouteImport } from './routes/_authenticated/inventory/quotation.add-to-invoice.$id'
import { Route as AuthenticatedInventoryPurchaseViewIdRouteImport } from './routes/_authenticated/inventory/purchase.view.$id'
import { Route as AuthenticatedInventoryPurchaseEditIdRouteImport } from './routes/_authenticated/inventory/purchase.edit.$id'
import { Route as AuthenticatedInventoryProductEditIdRouteImport } from './routes/_authenticated/inventory/product.edit.$id'
import { Route as AuthenticatedInventoryMerchantEditIdRouteImport } from './routes/_authenticated/inventory/merchant.edit.$id'
import { Route as AuthenticatedInventoryContactUsReplyIdRouteImport } from './routes/_authenticated/inventory/contact-us.reply.$id'
import { Route as AuthenticatedInventoryReturnVendorDetailsIdRouteImport } from './routes/_authenticated/inventory/return.vendor.details.$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedInventoryWarehouseIndexRoute =
  AuthenticatedInventoryWarehouseIndexRouteImport.update({
    id: '/inventory/warehouse/',
    path: '/inventory/warehouse/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryVendorsIndexRoute =
  AuthenticatedInventoryVendorsIndexRouteImport.update({
    id: '/inventory/vendors/',
    path: '/inventory/vendors/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryServiceIndexRoute =
  AuthenticatedInventoryServiceIndexRouteImport.update({
    id: '/inventory/service/',
    path: '/inventory/service/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryServiceInvoiceIndexRoute =
  AuthenticatedInventoryServiceInvoiceIndexRouteImport.update({
    id: '/inventory/service-invoice/',
    path: '/inventory/service-invoice/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventorySalesIndexRoute =
  AuthenticatedInventorySalesIndexRouteImport.update({
    id: '/inventory/sales/',
    path: '/inventory/sales/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryQuotationIndexRoute =
  AuthenticatedInventoryQuotationIndexRouteImport.update({
    id: '/inventory/quotation/',
    path: '/inventory/quotation/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryPurchaseIndexRoute =
  AuthenticatedInventoryPurchaseIndexRouteImport.update({
    id: '/inventory/purchase/',
    path: '/inventory/purchase/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryProductIndexRoute =
  AuthenticatedInventoryProductIndexRouteImport.update({
    id: '/inventory/product/',
    path: '/inventory/product/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryMerchantIndexRoute =
  AuthenticatedInventoryMerchantIndexRouteImport.update({
    id: '/inventory/merchant/',
    path: '/inventory/merchant/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryWarehouseStockMovementRoute =
  AuthenticatedInventoryWarehouseStockMovementRouteImport.update({
    id: '/inventory/warehouse/stock-movement',
    path: '/inventory/warehouse/stock-movement',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryWarehouseCreateRoute =
  AuthenticatedInventoryWarehouseCreateRouteImport.update({
    id: '/inventory/warehouse/create',
    path: '/inventory/warehouse/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryVendorsCreateRoute =
  AuthenticatedInventoryVendorsCreateRouteImport.update({
    id: '/inventory/vendors/create',
    path: '/inventory/vendors/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryServiceInvoiceCreateRoute =
  AuthenticatedInventoryServiceInvoiceCreateRouteImport.update({
    id: '/inventory/service-invoice/create',
    path: '/inventory/service-invoice/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventorySalesTermsRoute =
  AuthenticatedInventorySalesTermsRouteImport.update({
    id: '/inventory/sales/terms',
    path: '/inventory/sales/terms',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventorySalesPaymentsRoute =
  AuthenticatedInventorySalesPaymentsRouteImport.update({
    id: '/inventory/sales/payments',
    path: '/inventory/sales/payments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventorySalesCreateRoute =
  AuthenticatedInventorySalesCreateRouteImport.update({
    id: '/inventory/sales/create',
    path: '/inventory/sales/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventorySalesContactUsRoute =
  AuthenticatedInventorySalesContactUsRouteImport.update({
    id: '/inventory/sales/contact-us',
    path: '/inventory/sales/contact-us',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryQuotationCreateRoute =
  AuthenticatedInventoryQuotationCreateRouteImport.update({
    id: '/inventory/quotation/create',
    path: '/inventory/quotation/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryPurchaseCreateRoute =
  AuthenticatedInventoryPurchaseCreateRouteImport.update({
    id: '/inventory/purchase/create',
    path: '/inventory/purchase/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryProductUnitRoute =
  AuthenticatedInventoryProductUnitRouteImport.update({
    id: '/inventory/product/unit',
    path: '/inventory/product/unit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryProductSubCategoryRoute =
  AuthenticatedInventoryProductSubCategoryRouteImport.update({
    id: '/inventory/product/sub-category',
    path: '/inventory/product/sub-category',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryProductCreateRoute =
  AuthenticatedInventoryProductCreateRouteImport.update({
    id: '/inventory/product/create',
    path: '/inventory/product/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryProductCategoryRoute =
  AuthenticatedInventoryProductCategoryRouteImport.update({
    id: '/inventory/product/category',
    path: '/inventory/product/category',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryMerchantCreateRoute =
  AuthenticatedInventoryMerchantCreateRouteImport.update({
    id: '/inventory/merchant/create',
    path: '/inventory/merchant/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryReturnWastageIndexRoute =
  AuthenticatedInventoryReturnWastageIndexRouteImport.update({
    id: '/inventory/return/wastage/',
    path: '/inventory/return/wastage/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryReturnVendorIndexRoute =
  AuthenticatedInventoryReturnVendorIndexRouteImport.update({
    id: '/inventory/return/vendor/',
    path: '/inventory/return/vendor/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryReturnMerchantIndexRoute =
  AuthenticatedInventoryReturnMerchantIndexRouteImport.update({
    id: '/inventory/return/merchant/',
    path: '/inventory/return/merchant/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryWarehouseStockMovementCreateRoute =
  AuthenticatedInventoryWarehouseStockMovementCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedInventoryWarehouseStockMovementRoute,
  } as any)
const AuthenticatedInventoryWarehouseEditIdRoute =
  AuthenticatedInventoryWarehouseEditIdRouteImport.update({
    id: '/inventory/warehouse/edit/$id',
    path: '/inventory/warehouse/edit/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryVendorsEditIdRoute =
  AuthenticatedInventoryVendorsEditIdRouteImport.update({
    id: '/inventory/vendors/edit/$id',
    path: '/inventory/vendors/edit/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryServiceInvoiceViewIdRoute =
  AuthenticatedInventoryServiceInvoiceViewIdRouteImport.update({
    id: '/inventory/service-invoice/view/$id',
    path: '/inventory/service-invoice/view/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryServiceInvoiceEditIdRoute =
  AuthenticatedInventoryServiceInvoiceEditIdRouteImport.update({
    id: '/inventory/service-invoice/edit/$id',
    path: '/inventory/service-invoice/edit/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventorySalesViewIdRoute =
  AuthenticatedInventorySalesViewIdRouteImport.update({
    id: '/inventory/sales/view/$id',
    path: '/inventory/sales/view/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventorySalesPrintIdRoute =
  AuthenticatedInventorySalesPrintIdRouteImport.update({
    id: '/inventory/sales/print/$id',
    path: '/inventory/sales/print/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventorySalesEditIdRoute =
  AuthenticatedInventorySalesEditIdRouteImport.update({
    id: '/inventory/sales/edit/$id',
    path: '/inventory/sales/edit/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryReturnVendorCreateRoute =
  AuthenticatedInventoryReturnVendorCreateRouteImport.update({
    id: '/inventory/return/vendor/create',
    path: '/inventory/return/vendor/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryQuotationViewIdRoute =
  AuthenticatedInventoryQuotationViewIdRouteImport.update({
    id: '/inventory/quotation/view/$id',
    path: '/inventory/quotation/view/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryQuotationEditIdRoute =
  AuthenticatedInventoryQuotationEditIdRouteImport.update({
    id: '/inventory/quotation/edit/$id',
    path: '/inventory/quotation/edit/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryQuotationAddToInvoiceIdRoute =
  AuthenticatedInventoryQuotationAddToInvoiceIdRouteImport.update({
    id: '/inventory/quotation/add-to-invoice/$id',
    path: '/inventory/quotation/add-to-invoice/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryPurchaseViewIdRoute =
  AuthenticatedInventoryPurchaseViewIdRouteImport.update({
    id: '/inventory/purchase/view/$id',
    path: '/inventory/purchase/view/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryPurchaseEditIdRoute =
  AuthenticatedInventoryPurchaseEditIdRouteImport.update({
    id: '/inventory/purchase/edit/$id',
    path: '/inventory/purchase/edit/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryProductEditIdRoute =
  AuthenticatedInventoryProductEditIdRouteImport.update({
    id: '/inventory/product/edit/$id',
    path: '/inventory/product/edit/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryMerchantEditIdRoute =
  AuthenticatedInventoryMerchantEditIdRouteImport.update({
    id: '/inventory/merchant/edit/$id',
    path: '/inventory/merchant/edit/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryContactUsReplyIdRoute =
  AuthenticatedInventoryContactUsReplyIdRouteImport.update({
    id: '/inventory/contact-us/reply/$id',
    path: '/inventory/contact-us/reply/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryReturnVendorDetailsIdRoute =
  AuthenticatedInventoryReturnVendorDetailsIdRouteImport.update({
    id: '/inventory/return/vendor/details/$id',
    path: '/inventory/return/vendor/details/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/inventory/merchant/create': typeof AuthenticatedInventoryMerchantCreateRoute
  '/inventory/product/category': typeof AuthenticatedInventoryProductCategoryRoute
  '/inventory/product/create': typeof AuthenticatedInventoryProductCreateRoute
  '/inventory/product/sub-category': typeof AuthenticatedInventoryProductSubCategoryRoute
  '/inventory/product/unit': typeof AuthenticatedInventoryProductUnitRoute
  '/inventory/purchase/create': typeof AuthenticatedInventoryPurchaseCreateRoute
  '/inventory/quotation/create': typeof AuthenticatedInventoryQuotationCreateRoute
  '/inventory/sales/contact-us': typeof AuthenticatedInventorySalesContactUsRoute
  '/inventory/sales/create': typeof AuthenticatedInventorySalesCreateRoute
  '/inventory/sales/payments': typeof AuthenticatedInventorySalesPaymentsRoute
  '/inventory/sales/terms': typeof AuthenticatedInventorySalesTermsRoute
  '/inventory/service-invoice/create': typeof AuthenticatedInventoryServiceInvoiceCreateRoute
  '/inventory/vendors/create': typeof AuthenticatedInventoryVendorsCreateRoute
  '/inventory/warehouse/create': typeof AuthenticatedInventoryWarehouseCreateRoute
  '/inventory/warehouse/stock-movement': typeof AuthenticatedInventoryWarehouseStockMovementRouteWithChildren
  '/inventory/merchant/': typeof AuthenticatedInventoryMerchantIndexRoute
  '/inventory/product/': typeof AuthenticatedInventoryProductIndexRoute
  '/inventory/purchase/': typeof AuthenticatedInventoryPurchaseIndexRoute
  '/inventory/quotation/': typeof AuthenticatedInventoryQuotationIndexRoute
  '/inventory/sales/': typeof AuthenticatedInventorySalesIndexRoute
  '/inventory/service-invoice/': typeof AuthenticatedInventoryServiceInvoiceIndexRoute
  '/inventory/service/': typeof AuthenticatedInventoryServiceIndexRoute
  '/inventory/vendors/': typeof AuthenticatedInventoryVendorsIndexRoute
  '/inventory/warehouse/': typeof AuthenticatedInventoryWarehouseIndexRoute
  '/inventory/contact-us/reply/$id': typeof AuthenticatedInventoryContactUsReplyIdRoute
  '/inventory/merchant/edit/$id': typeof AuthenticatedInventoryMerchantEditIdRoute
  '/inventory/product/edit/$id': typeof AuthenticatedInventoryProductEditIdRoute
  '/inventory/purchase/edit/$id': typeof AuthenticatedInventoryPurchaseEditIdRoute
  '/inventory/purchase/view/$id': typeof AuthenticatedInventoryPurchaseViewIdRoute
  '/inventory/quotation/add-to-invoice/$id': typeof AuthenticatedInventoryQuotationAddToInvoiceIdRoute
  '/inventory/quotation/edit/$id': typeof AuthenticatedInventoryQuotationEditIdRoute
  '/inventory/quotation/view/$id': typeof AuthenticatedInventoryQuotationViewIdRoute
  '/inventory/return/vendor/create': typeof AuthenticatedInventoryReturnVendorCreateRoute
  '/inventory/sales/edit/$id': typeof AuthenticatedInventorySalesEditIdRoute
  '/inventory/sales/print/$id': typeof AuthenticatedInventorySalesPrintIdRoute
  '/inventory/sales/view/$id': typeof AuthenticatedInventorySalesViewIdRoute
  '/inventory/service-invoice/edit/$id': typeof AuthenticatedInventoryServiceInvoiceEditIdRoute
  '/inventory/service-invoice/view/$id': typeof AuthenticatedInventoryServiceInvoiceViewIdRoute
  '/inventory/vendors/edit/$id': typeof AuthenticatedInventoryVendorsEditIdRoute
  '/inventory/warehouse/edit/$id': typeof AuthenticatedInventoryWarehouseEditIdRoute
  '/inventory/warehouse/stock-movement/create': typeof AuthenticatedInventoryWarehouseStockMovementCreateRoute
  '/inventory/return/merchant/': typeof AuthenticatedInventoryReturnMerchantIndexRoute
  '/inventory/return/vendor/': typeof AuthenticatedInventoryReturnVendorIndexRoute
  '/inventory/return/wastage/': typeof AuthenticatedInventoryReturnWastageIndexRoute
  '/inventory/return/vendor/details/$id': typeof AuthenticatedInventoryReturnVendorDetailsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/inventory/merchant/create': typeof AuthenticatedInventoryMerchantCreateRoute
  '/inventory/product/category': typeof AuthenticatedInventoryProductCategoryRoute
  '/inventory/product/create': typeof AuthenticatedInventoryProductCreateRoute
  '/inventory/product/sub-category': typeof AuthenticatedInventoryProductSubCategoryRoute
  '/inventory/product/unit': typeof AuthenticatedInventoryProductUnitRoute
  '/inventory/purchase/create': typeof AuthenticatedInventoryPurchaseCreateRoute
  '/inventory/quotation/create': typeof AuthenticatedInventoryQuotationCreateRoute
  '/inventory/sales/contact-us': typeof AuthenticatedInventorySalesContactUsRoute
  '/inventory/sales/create': typeof AuthenticatedInventorySalesCreateRoute
  '/inventory/sales/payments': typeof AuthenticatedInventorySalesPaymentsRoute
  '/inventory/sales/terms': typeof AuthenticatedInventorySalesTermsRoute
  '/inventory/service-invoice/create': typeof AuthenticatedInventoryServiceInvoiceCreateRoute
  '/inventory/vendors/create': typeof AuthenticatedInventoryVendorsCreateRoute
  '/inventory/warehouse/create': typeof AuthenticatedInventoryWarehouseCreateRoute
  '/inventory/warehouse/stock-movement': typeof AuthenticatedInventoryWarehouseStockMovementRouteWithChildren
  '/inventory/merchant': typeof AuthenticatedInventoryMerchantIndexRoute
  '/inventory/product': typeof AuthenticatedInventoryProductIndexRoute
  '/inventory/purchase': typeof AuthenticatedInventoryPurchaseIndexRoute
  '/inventory/quotation': typeof AuthenticatedInventoryQuotationIndexRoute
  '/inventory/sales': typeof AuthenticatedInventorySalesIndexRoute
  '/inventory/service-invoice': typeof AuthenticatedInventoryServiceInvoiceIndexRoute
  '/inventory/service': typeof AuthenticatedInventoryServiceIndexRoute
  '/inventory/vendors': typeof AuthenticatedInventoryVendorsIndexRoute
  '/inventory/warehouse': typeof AuthenticatedInventoryWarehouseIndexRoute
  '/inventory/contact-us/reply/$id': typeof AuthenticatedInventoryContactUsReplyIdRoute
  '/inventory/merchant/edit/$id': typeof AuthenticatedInventoryMerchantEditIdRoute
  '/inventory/product/edit/$id': typeof AuthenticatedInventoryProductEditIdRoute
  '/inventory/purchase/edit/$id': typeof AuthenticatedInventoryPurchaseEditIdRoute
  '/inventory/purchase/view/$id': typeof AuthenticatedInventoryPurchaseViewIdRoute
  '/inventory/quotation/add-to-invoice/$id': typeof AuthenticatedInventoryQuotationAddToInvoiceIdRoute
  '/inventory/quotation/edit/$id': typeof AuthenticatedInventoryQuotationEditIdRoute
  '/inventory/quotation/view/$id': typeof AuthenticatedInventoryQuotationViewIdRoute
  '/inventory/return/vendor/create': typeof AuthenticatedInventoryReturnVendorCreateRoute
  '/inventory/sales/edit/$id': typeof AuthenticatedInventorySalesEditIdRoute
  '/inventory/sales/print/$id': typeof AuthenticatedInventorySalesPrintIdRoute
  '/inventory/sales/view/$id': typeof AuthenticatedInventorySalesViewIdRoute
  '/inventory/service-invoice/edit/$id': typeof AuthenticatedInventoryServiceInvoiceEditIdRoute
  '/inventory/service-invoice/view/$id': typeof AuthenticatedInventoryServiceInvoiceViewIdRoute
  '/inventory/vendors/edit/$id': typeof AuthenticatedInventoryVendorsEditIdRoute
  '/inventory/warehouse/edit/$id': typeof AuthenticatedInventoryWarehouseEditIdRoute
  '/inventory/warehouse/stock-movement/create': typeof AuthenticatedInventoryWarehouseStockMovementCreateRoute
  '/inventory/return/merchant': typeof AuthenticatedInventoryReturnMerchantIndexRoute
  '/inventory/return/vendor': typeof AuthenticatedInventoryReturnVendorIndexRoute
  '/inventory/return/wastage': typeof AuthenticatedInventoryReturnWastageIndexRoute
  '/inventory/return/vendor/details/$id': typeof AuthenticatedInventoryReturnVendorDetailsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/inventory/merchant/create': typeof AuthenticatedInventoryMerchantCreateRoute
  '/_authenticated/inventory/product/category': typeof AuthenticatedInventoryProductCategoryRoute
  '/_authenticated/inventory/product/create': typeof AuthenticatedInventoryProductCreateRoute
  '/_authenticated/inventory/product/sub-category': typeof AuthenticatedInventoryProductSubCategoryRoute
  '/_authenticated/inventory/product/unit': typeof AuthenticatedInventoryProductUnitRoute
  '/_authenticated/inventory/purchase/create': typeof AuthenticatedInventoryPurchaseCreateRoute
  '/_authenticated/inventory/quotation/create': typeof AuthenticatedInventoryQuotationCreateRoute
  '/_authenticated/inventory/sales/contact-us': typeof AuthenticatedInventorySalesContactUsRoute
  '/_authenticated/inventory/sales/create': typeof AuthenticatedInventorySalesCreateRoute
  '/_authenticated/inventory/sales/payments': typeof AuthenticatedInventorySalesPaymentsRoute
  '/_authenticated/inventory/sales/terms': typeof AuthenticatedInventorySalesTermsRoute
  '/_authenticated/inventory/service-invoice/create': typeof AuthenticatedInventoryServiceInvoiceCreateRoute
  '/_authenticated/inventory/vendors/create': typeof AuthenticatedInventoryVendorsCreateRoute
  '/_authenticated/inventory/warehouse/create': typeof AuthenticatedInventoryWarehouseCreateRoute
  '/_authenticated/inventory/warehouse/stock-movement': typeof AuthenticatedInventoryWarehouseStockMovementRouteWithChildren
  '/_authenticated/inventory/merchant/': typeof AuthenticatedInventoryMerchantIndexRoute
  '/_authenticated/inventory/product/': typeof AuthenticatedInventoryProductIndexRoute
  '/_authenticated/inventory/purchase/': typeof AuthenticatedInventoryPurchaseIndexRoute
  '/_authenticated/inventory/quotation/': typeof AuthenticatedInventoryQuotationIndexRoute
  '/_authenticated/inventory/sales/': typeof AuthenticatedInventorySalesIndexRoute
  '/_authenticated/inventory/service-invoice/': typeof AuthenticatedInventoryServiceInvoiceIndexRoute
  '/_authenticated/inventory/service/': typeof AuthenticatedInventoryServiceIndexRoute
  '/_authenticated/inventory/vendors/': typeof AuthenticatedInventoryVendorsIndexRoute
  '/_authenticated/inventory/warehouse/': typeof AuthenticatedInventoryWarehouseIndexRoute
  '/_authenticated/inventory/contact-us/reply/$id': typeof AuthenticatedInventoryContactUsReplyIdRoute
  '/_authenticated/inventory/merchant/edit/$id': typeof AuthenticatedInventoryMerchantEditIdRoute
  '/_authenticated/inventory/product/edit/$id': typeof AuthenticatedInventoryProductEditIdRoute
  '/_authenticated/inventory/purchase/edit/$id': typeof AuthenticatedInventoryPurchaseEditIdRoute
  '/_authenticated/inventory/purchase/view/$id': typeof AuthenticatedInventoryPurchaseViewIdRoute
  '/_authenticated/inventory/quotation/add-to-invoice/$id': typeof AuthenticatedInventoryQuotationAddToInvoiceIdRoute
  '/_authenticated/inventory/quotation/edit/$id': typeof AuthenticatedInventoryQuotationEditIdRoute
  '/_authenticated/inventory/quotation/view/$id': typeof AuthenticatedInventoryQuotationViewIdRoute
  '/_authenticated/inventory/return/vendor/create': typeof AuthenticatedInventoryReturnVendorCreateRoute
  '/_authenticated/inventory/sales/edit/$id': typeof AuthenticatedInventorySalesEditIdRoute
  '/_authenticated/inventory/sales/print/$id': typeof AuthenticatedInventorySalesPrintIdRoute
  '/_authenticated/inventory/sales/view/$id': typeof AuthenticatedInventorySalesViewIdRoute
  '/_authenticated/inventory/service-invoice/edit/$id': typeof AuthenticatedInventoryServiceInvoiceEditIdRoute
  '/_authenticated/inventory/service-invoice/view/$id': typeof AuthenticatedInventoryServiceInvoiceViewIdRoute
  '/_authenticated/inventory/vendors/edit/$id': typeof AuthenticatedInventoryVendorsEditIdRoute
  '/_authenticated/inventory/warehouse/edit/$id': typeof AuthenticatedInventoryWarehouseEditIdRoute
  '/_authenticated/inventory/warehouse/stock-movement/create': typeof AuthenticatedInventoryWarehouseStockMovementCreateRoute
  '/_authenticated/inventory/return/merchant/': typeof AuthenticatedInventoryReturnMerchantIndexRoute
  '/_authenticated/inventory/return/vendor/': typeof AuthenticatedInventoryReturnVendorIndexRoute
  '/_authenticated/inventory/return/wastage/': typeof AuthenticatedInventoryReturnWastageIndexRoute
  '/_authenticated/inventory/return/vendor/details/$id': typeof AuthenticatedInventoryReturnVendorDetailsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/inventory/merchant/create'
    | '/inventory/product/category'
    | '/inventory/product/create'
    | '/inventory/product/sub-category'
    | '/inventory/product/unit'
    | '/inventory/purchase/create'
    | '/inventory/quotation/create'
    | '/inventory/sales/contact-us'
    | '/inventory/sales/create'
    | '/inventory/sales/payments'
    | '/inventory/sales/terms'
    | '/inventory/service-invoice/create'
    | '/inventory/vendors/create'
    | '/inventory/warehouse/create'
    | '/inventory/warehouse/stock-movement'
    | '/inventory/merchant/'
    | '/inventory/product/'
    | '/inventory/purchase/'
    | '/inventory/quotation/'
    | '/inventory/sales/'
    | '/inventory/service-invoice/'
    | '/inventory/service/'
    | '/inventory/vendors/'
    | '/inventory/warehouse/'
    | '/inventory/contact-us/reply/$id'
    | '/inventory/merchant/edit/$id'
    | '/inventory/product/edit/$id'
    | '/inventory/purchase/edit/$id'
    | '/inventory/purchase/view/$id'
    | '/inventory/quotation/add-to-invoice/$id'
    | '/inventory/quotation/edit/$id'
    | '/inventory/quotation/view/$id'
    | '/inventory/return/vendor/create'
    | '/inventory/sales/edit/$id'
    | '/inventory/sales/print/$id'
    | '/inventory/sales/view/$id'
    | '/inventory/service-invoice/edit/$id'
    | '/inventory/service-invoice/view/$id'
    | '/inventory/vendors/edit/$id'
    | '/inventory/warehouse/edit/$id'
    | '/inventory/warehouse/stock-movement/create'
    | '/inventory/return/merchant/'
    | '/inventory/return/vendor/'
    | '/inventory/return/wastage/'
    | '/inventory/return/vendor/details/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/inventory/merchant/create'
    | '/inventory/product/category'
    | '/inventory/product/create'
    | '/inventory/product/sub-category'
    | '/inventory/product/unit'
    | '/inventory/purchase/create'
    | '/inventory/quotation/create'
    | '/inventory/sales/contact-us'
    | '/inventory/sales/create'
    | '/inventory/sales/payments'
    | '/inventory/sales/terms'
    | '/inventory/service-invoice/create'
    | '/inventory/vendors/create'
    | '/inventory/warehouse/create'
    | '/inventory/warehouse/stock-movement'
    | '/inventory/merchant'
    | '/inventory/product'
    | '/inventory/purchase'
    | '/inventory/quotation'
    | '/inventory/sales'
    | '/inventory/service-invoice'
    | '/inventory/service'
    | '/inventory/vendors'
    | '/inventory/warehouse'
    | '/inventory/contact-us/reply/$id'
    | '/inventory/merchant/edit/$id'
    | '/inventory/product/edit/$id'
    | '/inventory/purchase/edit/$id'
    | '/inventory/purchase/view/$id'
    | '/inventory/quotation/add-to-invoice/$id'
    | '/inventory/quotation/edit/$id'
    | '/inventory/quotation/view/$id'
    | '/inventory/return/vendor/create'
    | '/inventory/sales/edit/$id'
    | '/inventory/sales/print/$id'
    | '/inventory/sales/view/$id'
    | '/inventory/service-invoice/edit/$id'
    | '/inventory/service-invoice/view/$id'
    | '/inventory/vendors/edit/$id'
    | '/inventory/warehouse/edit/$id'
    | '/inventory/warehouse/stock-movement/create'
    | '/inventory/return/merchant'
    | '/inventory/return/vendor'
    | '/inventory/return/wastage'
    | '/inventory/return/vendor/details/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_authenticated/'
    | '/_authenticated/inventory/merchant/create'
    | '/_authenticated/inventory/product/category'
    | '/_authenticated/inventory/product/create'
    | '/_authenticated/inventory/product/sub-category'
    | '/_authenticated/inventory/product/unit'
    | '/_authenticated/inventory/purchase/create'
    | '/_authenticated/inventory/quotation/create'
    | '/_authenticated/inventory/sales/contact-us'
    | '/_authenticated/inventory/sales/create'
    | '/_authenticated/inventory/sales/payments'
    | '/_authenticated/inventory/sales/terms'
    | '/_authenticated/inventory/service-invoice/create'
    | '/_authenticated/inventory/vendors/create'
    | '/_authenticated/inventory/warehouse/create'
    | '/_authenticated/inventory/warehouse/stock-movement'
    | '/_authenticated/inventory/merchant/'
    | '/_authenticated/inventory/product/'
    | '/_authenticated/inventory/purchase/'
    | '/_authenticated/inventory/quotation/'
    | '/_authenticated/inventory/sales/'
    | '/_authenticated/inventory/service-invoice/'
    | '/_authenticated/inventory/service/'
    | '/_authenticated/inventory/vendors/'
    | '/_authenticated/inventory/warehouse/'
    | '/_authenticated/inventory/contact-us/reply/$id'
    | '/_authenticated/inventory/merchant/edit/$id'
    | '/_authenticated/inventory/product/edit/$id'
    | '/_authenticated/inventory/purchase/edit/$id'
    | '/_authenticated/inventory/purchase/view/$id'
    | '/_authenticated/inventory/quotation/add-to-invoice/$id'
    | '/_authenticated/inventory/quotation/edit/$id'
    | '/_authenticated/inventory/quotation/view/$id'
    | '/_authenticated/inventory/return/vendor/create'
    | '/_authenticated/inventory/sales/edit/$id'
    | '/_authenticated/inventory/sales/print/$id'
    | '/_authenticated/inventory/sales/view/$id'
    | '/_authenticated/inventory/service-invoice/edit/$id'
    | '/_authenticated/inventory/service-invoice/view/$id'
    | '/_authenticated/inventory/vendors/edit/$id'
    | '/_authenticated/inventory/warehouse/edit/$id'
    | '/_authenticated/inventory/warehouse/stock-movement/create'
    | '/_authenticated/inventory/return/merchant/'
    | '/_authenticated/inventory/return/vendor/'
    | '/_authenticated/inventory/return/wastage/'
    | '/_authenticated/inventory/return/vendor/details/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/inventory/warehouse/': {
      id: '/_authenticated/inventory/warehouse/'
      path: '/inventory/warehouse'
      fullPath: '/inventory/warehouse/'
      preLoaderRoute: typeof AuthenticatedInventoryWarehouseIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/vendors/': {
      id: '/_authenticated/inventory/vendors/'
      path: '/inventory/vendors'
      fullPath: '/inventory/vendors/'
      preLoaderRoute: typeof AuthenticatedInventoryVendorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/service/': {
      id: '/_authenticated/inventory/service/'
      path: '/inventory/service'
      fullPath: '/inventory/service/'
      preLoaderRoute: typeof AuthenticatedInventoryServiceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/service-invoice/': {
      id: '/_authenticated/inventory/service-invoice/'
      path: '/inventory/service-invoice'
      fullPath: '/inventory/service-invoice/'
      preLoaderRoute: typeof AuthenticatedInventoryServiceInvoiceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/sales/': {
      id: '/_authenticated/inventory/sales/'
      path: '/inventory/sales'
      fullPath: '/inventory/sales/'
      preLoaderRoute: typeof AuthenticatedInventorySalesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/quotation/': {
      id: '/_authenticated/inventory/quotation/'
      path: '/inventory/quotation'
      fullPath: '/inventory/quotation/'
      preLoaderRoute: typeof AuthenticatedInventoryQuotationIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/purchase/': {
      id: '/_authenticated/inventory/purchase/'
      path: '/inventory/purchase'
      fullPath: '/inventory/purchase/'
      preLoaderRoute: typeof AuthenticatedInventoryPurchaseIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/product/': {
      id: '/_authenticated/inventory/product/'
      path: '/inventory/product'
      fullPath: '/inventory/product/'
      preLoaderRoute: typeof AuthenticatedInventoryProductIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/merchant/': {
      id: '/_authenticated/inventory/merchant/'
      path: '/inventory/merchant'
      fullPath: '/inventory/merchant/'
      preLoaderRoute: typeof AuthenticatedInventoryMerchantIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/warehouse/stock-movement': {
      id: '/_authenticated/inventory/warehouse/stock-movement'
      path: '/inventory/warehouse/stock-movement'
      fullPath: '/inventory/warehouse/stock-movement'
      preLoaderRoute: typeof AuthenticatedInventoryWarehouseStockMovementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/warehouse/create': {
      id: '/_authenticated/inventory/warehouse/create'
      path: '/inventory/warehouse/create'
      fullPath: '/inventory/warehouse/create'
      preLoaderRoute: typeof AuthenticatedInventoryWarehouseCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/vendors/create': {
      id: '/_authenticated/inventory/vendors/create'
      path: '/inventory/vendors/create'
      fullPath: '/inventory/vendors/create'
      preLoaderRoute: typeof AuthenticatedInventoryVendorsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/service-invoice/create': {
      id: '/_authenticated/inventory/service-invoice/create'
      path: '/inventory/service-invoice/create'
      fullPath: '/inventory/service-invoice/create'
      preLoaderRoute: typeof AuthenticatedInventoryServiceInvoiceCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/sales/terms': {
      id: '/_authenticated/inventory/sales/terms'
      path: '/inventory/sales/terms'
      fullPath: '/inventory/sales/terms'
      preLoaderRoute: typeof AuthenticatedInventorySalesTermsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/sales/payments': {
      id: '/_authenticated/inventory/sales/payments'
      path: '/inventory/sales/payments'
      fullPath: '/inventory/sales/payments'
      preLoaderRoute: typeof AuthenticatedInventorySalesPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/sales/create': {
      id: '/_authenticated/inventory/sales/create'
      path: '/inventory/sales/create'
      fullPath: '/inventory/sales/create'
      preLoaderRoute: typeof AuthenticatedInventorySalesCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/sales/contact-us': {
      id: '/_authenticated/inventory/sales/contact-us'
      path: '/inventory/sales/contact-us'
      fullPath: '/inventory/sales/contact-us'
      preLoaderRoute: typeof AuthenticatedInventorySalesContactUsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/quotation/create': {
      id: '/_authenticated/inventory/quotation/create'
      path: '/inventory/quotation/create'
      fullPath: '/inventory/quotation/create'
      preLoaderRoute: typeof AuthenticatedInventoryQuotationCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/purchase/create': {
      id: '/_authenticated/inventory/purchase/create'
      path: '/inventory/purchase/create'
      fullPath: '/inventory/purchase/create'
      preLoaderRoute: typeof AuthenticatedInventoryPurchaseCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/product/unit': {
      id: '/_authenticated/inventory/product/unit'
      path: '/inventory/product/unit'
      fullPath: '/inventory/product/unit'
      preLoaderRoute: typeof AuthenticatedInventoryProductUnitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/product/sub-category': {
      id: '/_authenticated/inventory/product/sub-category'
      path: '/inventory/product/sub-category'
      fullPath: '/inventory/product/sub-category'
      preLoaderRoute: typeof AuthenticatedInventoryProductSubCategoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/product/create': {
      id: '/_authenticated/inventory/product/create'
      path: '/inventory/product/create'
      fullPath: '/inventory/product/create'
      preLoaderRoute: typeof AuthenticatedInventoryProductCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/product/category': {
      id: '/_authenticated/inventory/product/category'
      path: '/inventory/product/category'
      fullPath: '/inventory/product/category'
      preLoaderRoute: typeof AuthenticatedInventoryProductCategoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/merchant/create': {
      id: '/_authenticated/inventory/merchant/create'
      path: '/inventory/merchant/create'
      fullPath: '/inventory/merchant/create'
      preLoaderRoute: typeof AuthenticatedInventoryMerchantCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/return/wastage/': {
      id: '/_authenticated/inventory/return/wastage/'
      path: '/inventory/return/wastage'
      fullPath: '/inventory/return/wastage/'
      preLoaderRoute: typeof AuthenticatedInventoryReturnWastageIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/return/vendor/': {
      id: '/_authenticated/inventory/return/vendor/'
      path: '/inventory/return/vendor'
      fullPath: '/inventory/return/vendor/'
      preLoaderRoute: typeof AuthenticatedInventoryReturnVendorIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/return/merchant/': {
      id: '/_authenticated/inventory/return/merchant/'
      path: '/inventory/return/merchant'
      fullPath: '/inventory/return/merchant/'
      preLoaderRoute: typeof AuthenticatedInventoryReturnMerchantIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/warehouse/stock-movement/create': {
      id: '/_authenticated/inventory/warehouse/stock-movement/create'
      path: '/create'
      fullPath: '/inventory/warehouse/stock-movement/create'
      preLoaderRoute: typeof AuthenticatedInventoryWarehouseStockMovementCreateRouteImport
      parentRoute: typeof AuthenticatedInventoryWarehouseStockMovementRoute
    }
    '/_authenticated/inventory/warehouse/edit/$id': {
      id: '/_authenticated/inventory/warehouse/edit/$id'
      path: '/inventory/warehouse/edit/$id'
      fullPath: '/inventory/warehouse/edit/$id'
      preLoaderRoute: typeof AuthenticatedInventoryWarehouseEditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/vendors/edit/$id': {
      id: '/_authenticated/inventory/vendors/edit/$id'
      path: '/inventory/vendors/edit/$id'
      fullPath: '/inventory/vendors/edit/$id'
      preLoaderRoute: typeof AuthenticatedInventoryVendorsEditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/service-invoice/view/$id': {
      id: '/_authenticated/inventory/service-invoice/view/$id'
      path: '/inventory/service-invoice/view/$id'
      fullPath: '/inventory/service-invoice/view/$id'
      preLoaderRoute: typeof AuthenticatedInventoryServiceInvoiceViewIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/service-invoice/edit/$id': {
      id: '/_authenticated/inventory/service-invoice/edit/$id'
      path: '/inventory/service-invoice/edit/$id'
      fullPath: '/inventory/service-invoice/edit/$id'
      preLoaderRoute: typeof AuthenticatedInventoryServiceInvoiceEditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/sales/view/$id': {
      id: '/_authenticated/inventory/sales/view/$id'
      path: '/inventory/sales/view/$id'
      fullPath: '/inventory/sales/view/$id'
      preLoaderRoute: typeof AuthenticatedInventorySalesViewIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/sales/print/$id': {
      id: '/_authenticated/inventory/sales/print/$id'
      path: '/inventory/sales/print/$id'
      fullPath: '/inventory/sales/print/$id'
      preLoaderRoute: typeof AuthenticatedInventorySalesPrintIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/sales/edit/$id': {
      id: '/_authenticated/inventory/sales/edit/$id'
      path: '/inventory/sales/edit/$id'
      fullPath: '/inventory/sales/edit/$id'
      preLoaderRoute: typeof AuthenticatedInventorySalesEditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/return/vendor/create': {
      id: '/_authenticated/inventory/return/vendor/create'
      path: '/inventory/return/vendor/create'
      fullPath: '/inventory/return/vendor/create'
      preLoaderRoute: typeof AuthenticatedInventoryReturnVendorCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/quotation/view/$id': {
      id: '/_authenticated/inventory/quotation/view/$id'
      path: '/inventory/quotation/view/$id'
      fullPath: '/inventory/quotation/view/$id'
      preLoaderRoute: typeof AuthenticatedInventoryQuotationViewIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/quotation/edit/$id': {
      id: '/_authenticated/inventory/quotation/edit/$id'
      path: '/inventory/quotation/edit/$id'
      fullPath: '/inventory/quotation/edit/$id'
      preLoaderRoute: typeof AuthenticatedInventoryQuotationEditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/quotation/add-to-invoice/$id': {
      id: '/_authenticated/inventory/quotation/add-to-invoice/$id'
      path: '/inventory/quotation/add-to-invoice/$id'
      fullPath: '/inventory/quotation/add-to-invoice/$id'
      preLoaderRoute: typeof AuthenticatedInventoryQuotationAddToInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/purchase/view/$id': {
      id: '/_authenticated/inventory/purchase/view/$id'
      path: '/inventory/purchase/view/$id'
      fullPath: '/inventory/purchase/view/$id'
      preLoaderRoute: typeof AuthenticatedInventoryPurchaseViewIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/purchase/edit/$id': {
      id: '/_authenticated/inventory/purchase/edit/$id'
      path: '/inventory/purchase/edit/$id'
      fullPath: '/inventory/purchase/edit/$id'
      preLoaderRoute: typeof AuthenticatedInventoryPurchaseEditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/product/edit/$id': {
      id: '/_authenticated/inventory/product/edit/$id'
      path: '/inventory/product/edit/$id'
      fullPath: '/inventory/product/edit/$id'
      preLoaderRoute: typeof AuthenticatedInventoryProductEditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/merchant/edit/$id': {
      id: '/_authenticated/inventory/merchant/edit/$id'
      path: '/inventory/merchant/edit/$id'
      fullPath: '/inventory/merchant/edit/$id'
      preLoaderRoute: typeof AuthenticatedInventoryMerchantEditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/contact-us/reply/$id': {
      id: '/_authenticated/inventory/contact-us/reply/$id'
      path: '/inventory/contact-us/reply/$id'
      fullPath: '/inventory/contact-us/reply/$id'
      preLoaderRoute: typeof AuthenticatedInventoryContactUsReplyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/return/vendor/details/$id': {
      id: '/_authenticated/inventory/return/vendor/details/$id'
      path: '/inventory/return/vendor/details/$id'
      fullPath: '/inventory/return/vendor/details/$id'
      preLoaderRoute: typeof AuthenticatedInventoryReturnVendorDetailsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedInventoryWarehouseStockMovementRouteChildren {
  AuthenticatedInventoryWarehouseStockMovementCreateRoute: typeof AuthenticatedInventoryWarehouseStockMovementCreateRoute
}

const AuthenticatedInventoryWarehouseStockMovementRouteChildren: AuthenticatedInventoryWarehouseStockMovementRouteChildren =
  {
    AuthenticatedInventoryWarehouseStockMovementCreateRoute:
      AuthenticatedInventoryWarehouseStockMovementCreateRoute,
  }

const AuthenticatedInventoryWarehouseStockMovementRouteWithChildren =
  AuthenticatedInventoryWarehouseStockMovementRoute._addFileChildren(
    AuthenticatedInventoryWarehouseStockMovementRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedInventoryMerchantCreateRoute: typeof AuthenticatedInventoryMerchantCreateRoute
  AuthenticatedInventoryProductCategoryRoute: typeof AuthenticatedInventoryProductCategoryRoute
  AuthenticatedInventoryProductCreateRoute: typeof AuthenticatedInventoryProductCreateRoute
  AuthenticatedInventoryProductSubCategoryRoute: typeof AuthenticatedInventoryProductSubCategoryRoute
  AuthenticatedInventoryProductUnitRoute: typeof AuthenticatedInventoryProductUnitRoute
  AuthenticatedInventoryPurchaseCreateRoute: typeof AuthenticatedInventoryPurchaseCreateRoute
  AuthenticatedInventoryQuotationCreateRoute: typeof AuthenticatedInventoryQuotationCreateRoute
  AuthenticatedInventorySalesContactUsRoute: typeof AuthenticatedInventorySalesContactUsRoute
  AuthenticatedInventorySalesCreateRoute: typeof AuthenticatedInventorySalesCreateRoute
  AuthenticatedInventorySalesPaymentsRoute: typeof AuthenticatedInventorySalesPaymentsRoute
  AuthenticatedInventorySalesTermsRoute: typeof AuthenticatedInventorySalesTermsRoute
  AuthenticatedInventoryServiceInvoiceCreateRoute: typeof AuthenticatedInventoryServiceInvoiceCreateRoute
  AuthenticatedInventoryVendorsCreateRoute: typeof AuthenticatedInventoryVendorsCreateRoute
  AuthenticatedInventoryWarehouseCreateRoute: typeof AuthenticatedInventoryWarehouseCreateRoute
  AuthenticatedInventoryWarehouseStockMovementRoute: typeof AuthenticatedInventoryWarehouseStockMovementRouteWithChildren
  AuthenticatedInventoryMerchantIndexRoute: typeof AuthenticatedInventoryMerchantIndexRoute
  AuthenticatedInventoryProductIndexRoute: typeof AuthenticatedInventoryProductIndexRoute
  AuthenticatedInventoryPurchaseIndexRoute: typeof AuthenticatedInventoryPurchaseIndexRoute
  AuthenticatedInventoryQuotationIndexRoute: typeof AuthenticatedInventoryQuotationIndexRoute
  AuthenticatedInventorySalesIndexRoute: typeof AuthenticatedInventorySalesIndexRoute
  AuthenticatedInventoryServiceInvoiceIndexRoute: typeof AuthenticatedInventoryServiceInvoiceIndexRoute
  AuthenticatedInventoryServiceIndexRoute: typeof AuthenticatedInventoryServiceIndexRoute
  AuthenticatedInventoryVendorsIndexRoute: typeof AuthenticatedInventoryVendorsIndexRoute
  AuthenticatedInventoryWarehouseIndexRoute: typeof AuthenticatedInventoryWarehouseIndexRoute
  AuthenticatedInventoryContactUsReplyIdRoute: typeof AuthenticatedInventoryContactUsReplyIdRoute
  AuthenticatedInventoryMerchantEditIdRoute: typeof AuthenticatedInventoryMerchantEditIdRoute
  AuthenticatedInventoryProductEditIdRoute: typeof AuthenticatedInventoryProductEditIdRoute
  AuthenticatedInventoryPurchaseEditIdRoute: typeof AuthenticatedInventoryPurchaseEditIdRoute
  AuthenticatedInventoryPurchaseViewIdRoute: typeof AuthenticatedInventoryPurchaseViewIdRoute
  AuthenticatedInventoryQuotationAddToInvoiceIdRoute: typeof AuthenticatedInventoryQuotationAddToInvoiceIdRoute
  AuthenticatedInventoryQuotationEditIdRoute: typeof AuthenticatedInventoryQuotationEditIdRoute
  AuthenticatedInventoryQuotationViewIdRoute: typeof AuthenticatedInventoryQuotationViewIdRoute
  AuthenticatedInventoryReturnVendorCreateRoute: typeof AuthenticatedInventoryReturnVendorCreateRoute
  AuthenticatedInventorySalesEditIdRoute: typeof AuthenticatedInventorySalesEditIdRoute
  AuthenticatedInventorySalesPrintIdRoute: typeof AuthenticatedInventorySalesPrintIdRoute
  AuthenticatedInventorySalesViewIdRoute: typeof AuthenticatedInventorySalesViewIdRoute
  AuthenticatedInventoryServiceInvoiceEditIdRoute: typeof AuthenticatedInventoryServiceInvoiceEditIdRoute
  AuthenticatedInventoryServiceInvoiceViewIdRoute: typeof AuthenticatedInventoryServiceInvoiceViewIdRoute
  AuthenticatedInventoryVendorsEditIdRoute: typeof AuthenticatedInventoryVendorsEditIdRoute
  AuthenticatedInventoryWarehouseEditIdRoute: typeof AuthenticatedInventoryWarehouseEditIdRoute
  AuthenticatedInventoryReturnMerchantIndexRoute: typeof AuthenticatedInventoryReturnMerchantIndexRoute
  AuthenticatedInventoryReturnVendorIndexRoute: typeof AuthenticatedInventoryReturnVendorIndexRoute
  AuthenticatedInventoryReturnWastageIndexRoute: typeof AuthenticatedInventoryReturnWastageIndexRoute
  AuthenticatedInventoryReturnVendorDetailsIdRoute: typeof AuthenticatedInventoryReturnVendorDetailsIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedInventoryMerchantCreateRoute:
    AuthenticatedInventoryMerchantCreateRoute,
  AuthenticatedInventoryProductCategoryRoute:
    AuthenticatedInventoryProductCategoryRoute,
  AuthenticatedInventoryProductCreateRoute:
    AuthenticatedInventoryProductCreateRoute,
  AuthenticatedInventoryProductSubCategoryRoute:
    AuthenticatedInventoryProductSubCategoryRoute,
  AuthenticatedInventoryProductUnitRoute:
    AuthenticatedInventoryProductUnitRoute,
  AuthenticatedInventoryPurchaseCreateRoute:
    AuthenticatedInventoryPurchaseCreateRoute,
  AuthenticatedInventoryQuotationCreateRoute:
    AuthenticatedInventoryQuotationCreateRoute,
  AuthenticatedInventorySalesContactUsRoute:
    AuthenticatedInventorySalesContactUsRoute,
  AuthenticatedInventorySalesCreateRoute:
    AuthenticatedInventorySalesCreateRoute,
  AuthenticatedInventorySalesPaymentsRoute:
    AuthenticatedInventorySalesPaymentsRoute,
  AuthenticatedInventorySalesTermsRoute: AuthenticatedInventorySalesTermsRoute,
  AuthenticatedInventoryServiceInvoiceCreateRoute:
    AuthenticatedInventoryServiceInvoiceCreateRoute,
  AuthenticatedInventoryVendorsCreateRoute:
    AuthenticatedInventoryVendorsCreateRoute,
  AuthenticatedInventoryWarehouseCreateRoute:
    AuthenticatedInventoryWarehouseCreateRoute,
  AuthenticatedInventoryWarehouseStockMovementRoute:
    AuthenticatedInventoryWarehouseStockMovementRouteWithChildren,
  AuthenticatedInventoryMerchantIndexRoute:
    AuthenticatedInventoryMerchantIndexRoute,
  AuthenticatedInventoryProductIndexRoute:
    AuthenticatedInventoryProductIndexRoute,
  AuthenticatedInventoryPurchaseIndexRoute:
    AuthenticatedInventoryPurchaseIndexRoute,
  AuthenticatedInventoryQuotationIndexRoute:
    AuthenticatedInventoryQuotationIndexRoute,
  AuthenticatedInventorySalesIndexRoute: AuthenticatedInventorySalesIndexRoute,
  AuthenticatedInventoryServiceInvoiceIndexRoute:
    AuthenticatedInventoryServiceInvoiceIndexRoute,
  AuthenticatedInventoryServiceIndexRoute:
    AuthenticatedInventoryServiceIndexRoute,
  AuthenticatedInventoryVendorsIndexRoute:
    AuthenticatedInventoryVendorsIndexRoute,
  AuthenticatedInventoryWarehouseIndexRoute:
    AuthenticatedInventoryWarehouseIndexRoute,
  AuthenticatedInventoryContactUsReplyIdRoute:
    AuthenticatedInventoryContactUsReplyIdRoute,
  AuthenticatedInventoryMerchantEditIdRoute:
    AuthenticatedInventoryMerchantEditIdRoute,
  AuthenticatedInventoryProductEditIdRoute:
    AuthenticatedInventoryProductEditIdRoute,
  AuthenticatedInventoryPurchaseEditIdRoute:
    AuthenticatedInventoryPurchaseEditIdRoute,
  AuthenticatedInventoryPurchaseViewIdRoute:
    AuthenticatedInventoryPurchaseViewIdRoute,
  AuthenticatedInventoryQuotationAddToInvoiceIdRoute:
    AuthenticatedInventoryQuotationAddToInvoiceIdRoute,
  AuthenticatedInventoryQuotationEditIdRoute:
    AuthenticatedInventoryQuotationEditIdRoute,
  AuthenticatedInventoryQuotationViewIdRoute:
    AuthenticatedInventoryQuotationViewIdRoute,
  AuthenticatedInventoryReturnVendorCreateRoute:
    AuthenticatedInventoryReturnVendorCreateRoute,
  AuthenticatedInventorySalesEditIdRoute:
    AuthenticatedInventorySalesEditIdRoute,
  AuthenticatedInventorySalesPrintIdRoute:
    AuthenticatedInventorySalesPrintIdRoute,
  AuthenticatedInventorySalesViewIdRoute:
    AuthenticatedInventorySalesViewIdRoute,
  AuthenticatedInventoryServiceInvoiceEditIdRoute:
    AuthenticatedInventoryServiceInvoiceEditIdRoute,
  AuthenticatedInventoryServiceInvoiceViewIdRoute:
    AuthenticatedInventoryServiceInvoiceViewIdRoute,
  AuthenticatedInventoryVendorsEditIdRoute:
    AuthenticatedInventoryVendorsEditIdRoute,
  AuthenticatedInventoryWarehouseEditIdRoute:
    AuthenticatedInventoryWarehouseEditIdRoute,
  AuthenticatedInventoryReturnMerchantIndexRoute:
    AuthenticatedInventoryReturnMerchantIndexRoute,
  AuthenticatedInventoryReturnVendorIndexRoute:
    AuthenticatedInventoryReturnVendorIndexRoute,
  AuthenticatedInventoryReturnWastageIndexRoute:
    AuthenticatedInventoryReturnWastageIndexRoute,
  AuthenticatedInventoryReturnVendorDetailsIdRoute:
    AuthenticatedInventoryReturnVendorDetailsIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
