/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthenticatedInventoryTermsIndexRouteImport } from './routes/_authenticated/inventory/terms.index'
import { Route as AuthenticatedInventorySalesIndexRouteImport } from './routes/_authenticated/inventory/sales.index'
import { Route as AuthenticatedInventoryContactUsIndexRouteImport } from './routes/_authenticated/inventory/contact-us.index'
import { Route as AuthenticatedInventoryContactUsReplyIdRouteImport } from './routes/_authenticated/inventory/contact-us.reply.$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedInventoryTermsIndexRoute =
  AuthenticatedInventoryTermsIndexRouteImport.update({
    id: '/inventory/terms/',
    path: '/inventory/terms/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventorySalesIndexRoute =
  AuthenticatedInventorySalesIndexRouteImport.update({
    id: '/inventory/sales/',
    path: '/inventory/sales/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryContactUsIndexRoute =
  AuthenticatedInventoryContactUsIndexRouteImport.update({
    id: '/inventory/contact-us/',
    path: '/inventory/contact-us/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryContactUsReplyIdRoute =
  AuthenticatedInventoryContactUsReplyIdRouteImport.update({
    id: '/inventory/contact-us/reply/$id',
    path: '/inventory/contact-us/reply/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/inventory/contact-us/': typeof AuthenticatedInventoryContactUsIndexRoute
  '/inventory/sales/': typeof AuthenticatedInventorySalesIndexRoute
  '/inventory/terms/': typeof AuthenticatedInventoryTermsIndexRoute
  '/inventory/contact-us/reply/$id': typeof AuthenticatedInventoryContactUsReplyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/inventory/contact-us': typeof AuthenticatedInventoryContactUsIndexRoute
  '/inventory/sales': typeof AuthenticatedInventorySalesIndexRoute
  '/inventory/terms': typeof AuthenticatedInventoryTermsIndexRoute
  '/inventory/contact-us/reply/$id': typeof AuthenticatedInventoryContactUsReplyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/inventory/contact-us/': typeof AuthenticatedInventoryContactUsIndexRoute
  '/_authenticated/inventory/sales/': typeof AuthenticatedInventorySalesIndexRoute
  '/_authenticated/inventory/terms/': typeof AuthenticatedInventoryTermsIndexRoute
  '/_authenticated/inventory/contact-us/reply/$id': typeof AuthenticatedInventoryContactUsReplyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/inventory/contact-us/'
    | '/inventory/sales/'
    | '/inventory/terms/'
    | '/inventory/contact-us/reply/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/inventory/contact-us'
    | '/inventory/sales'
    | '/inventory/terms'
    | '/inventory/contact-us/reply/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_authenticated/'
    | '/_authenticated/inventory/contact-us/'
    | '/_authenticated/inventory/sales/'
    | '/_authenticated/inventory/terms/'
    | '/_authenticated/inventory/contact-us/reply/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/inventory/terms/': {
      id: '/_authenticated/inventory/terms/'
      path: '/inventory/terms'
      fullPath: '/inventory/terms/'
      preLoaderRoute: typeof AuthenticatedInventoryTermsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/sales/': {
      id: '/_authenticated/inventory/sales/'
      path: '/inventory/sales'
      fullPath: '/inventory/sales/'
      preLoaderRoute: typeof AuthenticatedInventorySalesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/contact-us/': {
      id: '/_authenticated/inventory/contact-us/'
      path: '/inventory/contact-us'
      fullPath: '/inventory/contact-us/'
      preLoaderRoute: typeof AuthenticatedInventoryContactUsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/contact-us/reply/$id': {
      id: '/_authenticated/inventory/contact-us/reply/$id'
      path: '/inventory/contact-us/reply/$id'
      fullPath: '/inventory/contact-us/reply/$id'
      preLoaderRoute: typeof AuthenticatedInventoryContactUsReplyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedInventoryContactUsIndexRoute: typeof AuthenticatedInventoryContactUsIndexRoute
  AuthenticatedInventorySalesIndexRoute: typeof AuthenticatedInventorySalesIndexRoute
  AuthenticatedInventoryTermsIndexRoute: typeof AuthenticatedInventoryTermsIndexRoute
  AuthenticatedInventoryContactUsReplyIdRoute: typeof AuthenticatedInventoryContactUsReplyIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedInventoryContactUsIndexRoute:
    AuthenticatedInventoryContactUsIndexRoute,
  AuthenticatedInventorySalesIndexRoute: AuthenticatedInventorySalesIndexRoute,
  AuthenticatedInventoryTermsIndexRoute: AuthenticatedInventoryTermsIndexRoute,
  AuthenticatedInventoryContactUsReplyIdRoute:
    AuthenticatedInventoryContactUsReplyIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
